In [1]:
import pandas as pd
import numpy as np
from dateutil.relativedelta import relativedelta
from datetime import date

%load_ext snakeviz

In [2]:
dtl = [date(2000, 1, 1)+relativedelta(days=i) for i in range(100)]

In [3]:
dti = pd.DatetimeIndex(start='01-01-2000', freq='d', periods=100)

In [4]:
dti.day

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=int32)

In [5]:
dti[0]

Timestamp('2000-01-01 00:00:00', freq='D')

In [6]:
dti[0].asm8

numpy.datetime64('2000-01-01T00:00:00.000000000')

In [7]:
dti.values + np.timedelta64(1, 'D')

array(['2000-01-02T00:00:00.000000000', '2000-01-03T00:00:00.000000000',
       '2000-01-04T00:00:00.000000000', '2000-01-05T00:00:00.000000000',
       '2000-01-06T00:00:00.000000000', '2000-01-07T00:00:00.000000000',
       '2000-01-08T00:00:00.000000000', '2000-01-09T00:00:00.000000000',
       '2000-01-10T00:00:00.000000000', '2000-01-11T00:00:00.000000000',
       '2000-01-12T00:00:00.000000000', '2000-01-13T00:00:00.000000000',
       '2000-01-14T00:00:00.000000000', '2000-01-15T00:00:00.000000000',
       '2000-01-16T00:00:00.000000000', '2000-01-17T00:00:00.000000000',
       '2000-01-18T00:00:00.000000000', '2000-01-19T00:00:00.000000000',
       '2000-01-20T00:00:00.000000000', '2000-01-21T00:00:00.000000000',
       '2000-01-22T00:00:00.000000000', '2000-01-23T00:00:00.000000000',
       '2000-01-24T00:00:00.000000000', '2000-01-25T00:00:00.000000000',
       '2000-01-26T00:00:00.000000000', '2000-01-27T00:00:00.000000000',
       '2000-01-28T00:00:00.000000000', '2000-01-29

In [8]:
dti.values + np.timedelta64(1, 'M')

TypeError: Cannot get a common metadata divisor for NumPy datetime metadata [ns] and [M] because they have incompatible nonlinear base time units

In [9]:
d = np.datetime64('2000-01-01')

In [10]:
d.astype(np.int)

10957

In [11]:
d = np.datetime64('2000-01-01', 'ns')

In [12]:
d.astype(np.int)

946684800000000000

In [13]:
dti.asi8

array([946684800000000000, 946771200000000000, 946857600000000000,
       946944000000000000, 947030400000000000, 947116800000000000,
       947203200000000000, 947289600000000000, 947376000000000000,
       947462400000000000, 947548800000000000, 947635200000000000,
       947721600000000000, 947808000000000000, 947894400000000000,
       947980800000000000, 948067200000000000, 948153600000000000,
       948240000000000000, 948326400000000000, 948412800000000000,
       948499200000000000, 948585600000000000, 948672000000000000,
       948758400000000000, 948844800000000000, 948931200000000000,
       949017600000000000, 949104000000000000, 949190400000000000,
       949276800000000000, 949363200000000000, 949449600000000000,
       949536000000000000, 949622400000000000, 949708800000000000,
       949795200000000000, 949881600000000000, 949968000000000000,
       950054400000000000, 950140800000000000, 950227200000000000,
       950313600000000000, 950400000000000000, 950486400000000

In [14]:
dti.asi8/(24*60*60*1E9)

array([ 10957.,  10958.,  10959.,  10960.,  10961.,  10962.,  10963.,
        10964.,  10965.,  10966.,  10967.,  10968.,  10969.,  10970.,
        10971.,  10972.,  10973.,  10974.,  10975.,  10976.,  10977.,
        10978.,  10979.,  10980.,  10981.,  10982.,  10983.,  10984.,
        10985.,  10986.,  10987.,  10988.,  10989.,  10990.,  10991.,
        10992.,  10993.,  10994.,  10995.,  10996.,  10997.,  10998.,
        10999.,  11000.,  11001.,  11002.,  11003.,  11004.,  11005.,
        11006.,  11007.,  11008.,  11009.,  11010.,  11011.,  11012.,
        11013.,  11014.,  11015.,  11016.,  11017.,  11018.,  11019.,
        11020.,  11021.,  11022.,  11023.,  11024.,  11025.,  11026.,
        11027.,  11028.,  11029.,  11030.,  11031.,  11032.,  11033.,
        11034.,  11035.,  11036.,  11037.,  11038.,  11039.,  11040.,
        11041.,  11042.,  11043.,  11044.,  11045.,  11046.,  11047.,
        11048.,  11049.,  11050.,  11051.,  11052.,  11053.,  11054.,
        11055.,  110

In [15]:
%snakeviz dti[0] + pd.DateOffset(years=1, months=1, days=29)

 
*** Profile stats marshalled to file '/tmp/tmph61y9tlt'. 


In [17]:
from custom_offsets import PrecomputedOffset

In [18]:
offset = PrecomputedOffset(years=1, months=1, days=29)

In [19]:
print(offset.offsets.dtypes)

base       int64
decades    int64
months     int64
years      int64
dtype: object


In [20]:
%timeit dti + pd.DateOffset(years=1, months=1, days=0)

The slowest run took 4.48 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 236 µs per loop


In [21]:
%timeit dti + PrecomputedOffset(years=1, months=1, days=0)

The slowest run took 12.60 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 70.8 µs per loop


In [22]:
%timeit dti[0] + pd.DateOffset(years=30, months=1, days=28)

The slowest run took 12.50 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 43.9 µs per loop


In [23]:
%timeit dti[0] + PrecomputedOffset(years=30, months=1, days=28)

The slowest run took 5.20 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 47.3 µs per loop


In [24]:
%snakeviz dti + PrecomputedOffset(years=39, months=7, days=28)

 
*** Profile stats marshalled to file '/tmp/tmp_p49srmk'. 
